finaltask/finalproject/finalapp/urls.py
from django.urls import path
from . import views
app_name='finalapp'
urlpatterns = [

    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('abc/',views.abc,name='abc'),
    path('details/',views.details,name='details'),
    path('final/',views.final,name='final')
]

finaltask/finalproject/finalproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("finalapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

finaltask/finalproject/finalapp/models.py
from django.db import models

# Create your models here.
class services(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    servicecharge = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

finaltask/finalproject/finalapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


from .models import services


# Create your views here.
def home(request):
    service = services.objects.all()
    context = {
        'bank_list': service
    }
    return render(request, "home.html", context)


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('finalapp:abc')
        else:
            messages.info(request, "invalid credentials")
            return render(request, 'login.html')

    return render(request, "login.html")

def register(request):
    if request.method == 'POST':
        username = request.POST['username']

        password = request.POST['password']
        cpassword = request.POST['password1']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                # messages.info(request, "username taken")
                return redirect('finalapp:register')

            else:
                user = User.objects.create_user(username=username, password=password)

                user.save();
                return redirect('finalapp:login')
                # print("user created")
        else:
            # message.info(request, "password not matching")
            return redirect('finalapp:register')
        return redirect('finalapp:home')
    return render(request, "register.html")





def abc(request):

    return render(request, 'abc.html')


def details(request):


    return render(request, 'details.html')



def final(request):
    return render(request, 'final.html')

finaltask/finalproject/templates/abc.html
{% extends 'base.html' %}
{% block body %}
<form action="abc" method="post">
    {% csrf_token %}
login success<br>

<!--<a  href="{% url 'finalapp:details' %}">-->
<!--    enter details-->
<!--</a>-->
    <a class="btn btn-warning" href="{% url 'finalapp:details'  %}">details</a>
</form>
{% endblock %}

finaltask/finalproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body>
{% include 'nav.html' %}

{% block body %}

{% endblock %}
</body>
</html>

finaltask/finalproject/templates/details.html
{% extends 'base.html' %}
{% block body %}

<form action="details"  method="POST">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter name"><br>
    <input type="date" name="date_of_birth" placeholder="enter date of birth"><br>
    <input type="number" name="age" placeholder="enter age"><br>
    <input type="text" name="gender" placeholder="enter gender"><br>
    <input type="number" name="phone_number" placeholder="enter phone number"><br>
    <input type="email" name="email" placeholder="enter email"><br>
    <input type="text" name="address" placeholder="enter address"><br>
    <div class="form-group col-md-3">
    <label for="input district">district</label>
    <select class="form-control" id="input district">
        <option value="select district">select district</option>
        <option value="alappuzha">alappuzha</option>
        <option value="ernakulam">ernakulam</option>
        <option value="idukki">idukki</option>
        <option value="kannur">kannur</option>
        <option value="kasargod">kasargod</option>
        <option value="kollam">kollam</option>
        <option value="kozhikode">kozhikode</option>
        <option value="kottayam">kottayam</option>
        <option value="malappuram">malappuram</option>
        <option value="palakkad">palakkad</option>
        <option value="pathanamthitta">pathanamthitta</option>
        <option value="thiruvananthapuram">thiruvananthapuram</option>
        <option value="thrissur">thrissur</option>
        <option value="wayanad">wayanad</option>

    </select><br>
    </div>

    <div class="form-group col-md-3">
    <label for="input zone">zone</label>
    <select class="form-control" id="input zone">
        <option value="select zone">select zone</option>
        <option value="cherthala">cherthala</option>
        <option value="haripad">haripad</option>
        <option value="aluva">aluva</option>
        <option value="edappally">edappally</option>
        <option value="thodupuzha">thodupuzha</option>
        <option value="devikulam">devikulam</option>
        <option value="payyanur">payyanur</option>
        <option value="iritty">iritty</option>
        <option value="kanhangad">kanhangad</option>
        <option value="nileshwar">nileshwar</option>
        <option value="thirumullavaram">thirumullavaram</option>
        <option value="karunagapally">karunagapally</option>
        <option value="beypore">beypore</option>
        <option value="feroke">feroke</option>
        <option value="pala">pala</option>
        <option value="vaikom">vaikom</option>
        <option value="manjeri">manjeri</option>
        <option value="ponnani">ponnani</option>
        <option value="kuzhalmannam">palakkad</option>
        <option value="pattambi">pattambi</option>
        <option value="adoor">adoor</option>
        <option value="ranni">ranni</option>
        <option value="attingal">attingal</option>
        <option value="neyyatinkara">neyyatinkara</option>
        <option value="chalakkudy">chalakkudy</option>
        <option value="irinjalakuda">irinjalakuda</option>
        <option value="mananthavady">mananthavadi</option>
        <option value="kalpetta">kalpetta</option>
    </select><br>
    </div>



    <div class="form-group col-md-3">
    <label for="input account_type">account_type</label>
    <select class="form-control" id="input account_type">
        <option value="select account_type">select account_type</option>
        <option value="savings">savings</option>
        <option value="current">current</option>
        <option value="joint">joint</option>
        <option value="salary">salary</option>
    </select><br>
    </div>

    <div>
    <label for="input materials_required">materials required</label><br>

    <input type="checkbox" value="credit_card"> credit card<br>

        <input type="checkbox" value="debit_card"> debit card<br>
        <input type="checkbox" value="online_banking"> online banking<br>
        <input type="checkbox" value="cheque_book"> cheque book<br>
    </label><br>

    </div>

    <a class="btn btn-warning" href="{% url 'finalapp:final'  %}">submit</a><br>
    <a class="btn btn-danger" href="{% url 'finalapp:home'  %}">logout</a>
</form>

{% endblock  %}

finaltask/finalproject/templates/final.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
application accepted.<br>
<a href="{% url 'finalapp:home' %}">
    back to home
</a>
</body>
</html>
{% endblock %}

finaltask/finalproject/templates/home.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for i in bank_list %}
        <div class="col-md-3 p-3">
            <div class="card" style="width:100%; height:100%;" >
  <img src="{{i.img.url}}" class="card-img-top"  alt="..." style="width:300px; height:250px;" >
  <div class="card-body" >
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}} </p>
      <p class="card-text">service charge is Rs:{{i.servicecharge}}/year </p>
    <a href="#" class="btn btn-primary">Apply Now</a>
  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

finaltask/finalproject/templates/login.html
{% extends 'base.html' %}

{% block body %}
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter username"><br>
    <input type="password" name="password" placeholder="enter password"><br>
    <input type="submit"><br>

    <a href="{% url 'finalapp:register' %}"> for registration click here</a>
</form>

{% endblock %}

finaltask/finalproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ABC BANKING SERVICES LTD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'finalapp:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-warning" href="{% url 'finalapp:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Register</a>
        </li>
        <li class="nav-item dropdown {% if 'finalapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Branches
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">palakkad</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">kollam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">thrissur</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad">wayanad</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">kottayam</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

finaltask/finalproject/templates/register.html
{% extends 'base.html' %}
{% block body %}

<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter username"><br>


    <input type="password" name="password" placeholder="enter password"><br>
    <input type="password" name="password1" placeholder="confirm password"><br>

    <input type="submit">


</form>

{% endblock %}